# document_processor/api.py

from __future__ import annotations

import asyncio
import logging
import re
import time
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import httpx
from fastapi import (
    BackgroundTasks,
    Depends,
    FastAPI,
    File,
    Form,
    HTTPException,
    Request,
    UploadFile,
)
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from pydantic_settings import BaseSettings

import logic  # tu módulo mejorado

logger = logging.getLogger(__name__)
if not logger.handlers:
    logging.basicConfig(level=logging.INFO)


# -----------------------------
# Helper para parsear páginas
# -----------------------------

def _extract_pages_from_text(text: str) -> List[Tuple[int, str]]:
    """
    Extrae páginas del texto que usa el formato '--- Página X ---'.
    """
    pattern = r'--- Página\s+(\d+)\s+---'
    parts = re.split(pattern, text)
    pages = []
    # Itera sobre los resultados del split para obtener pares (número, texto)
    for i in range(1, len(parts), 2):
        try:
            page_num = int(parts[i])
            page_text = parts[i + 1].strip()
            if page_text:  # Solo añade páginas con contenido
                pages.append((page_num, page_text))
        except (ValueError, IndexError):
            continue
    return pages


# -----------------------------
# Configuración (env-first)
# -----------------------------

class Settings(BaseSettings):
    llm_service_url: str = Field(default="http://127.0.0.1:8001")
    base_dir: Path = Field(default=Path.home() / "SmartDocData")
    enable_cors: bool = True
    cors_origins: List[str] = Field(default_factory=lambda: ["*"])
    require_api_key: bool = False
    api_key_header_name: str = "x-api-key"
    api_key_value: Optional[str] = None
    max_pdf_bytes: int = 30 * 1024 * 1024
    classify_snippet_len: int = 4000
    http_timeout_seconds: float = 20.0

    class Config:
        env_prefix = "SMARTDOC_"
        case_sensitive = False

def get_settings() -> Settings:
    s = Settings()
    s.base_dir.mkdir(parents=True, exist_ok=True)
    return s


# --------------------------------
# Seguridad simple por API Key
# --------------------------------

async def require_api_key(request: Request, settings: Settings = Depends(get_settings)):
    if not settings.require_api_key:
        return
    header_name = settings.api_key_header_name
    provided = request.headers.get(header_name)
    if not provided or settings.api_key_value is None or provided != settings.api_key_value:
        raise HTTPException(status_code=401, detail=f"API key inválida o ausente en header '{header_name}'.")


# -----------------------------
# App y middlewares
# -----------------------------

app = FastAPI(
    title="SmartDoc Document Processor",
    version="1.1",
    description="Microservicio para recibir, convertir, clasificar y almacenar documentos.",
)

settings_instance = get_settings()
if settings_instance.enable_cors:
    app.add_middleware(
        CORSMiddleware,
        allow_origins=settings_instance.cors_origins,
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
    )


# --------------------------------
# Modelos de respuesta / request
# --------------------------------

class ProcessResponse(BaseModel):
    message: str
    original_filename: str
    markdown_path: str
    pdf_path: str
    category: str
    summary_path: str


# --------------------------------
# HTTP utils
# --------------------------------

def _httpx_client(settings: Settings) -> httpx.AsyncClient:
    return httpx.AsyncClient(
        base_url=settings.llm_service_url,
        timeout=httpx.Timeout(settings.http_timeout_seconds),
        follow_redirects=True,
    )


# --------------------------------
# Background: crear y guardar resumen
# --------------------------------

async def _retry(coro_func, *args, retries: int = 2, delay: float = 1.0, **kwargs):
    last_exc = None
    for i in range(retries + 1):
        try:
            return await coro_func(*args, **kwargs)
        except Exception as e:
            last_exc = e
            if i < retries:
                await asyncio.sleep(delay)
    raise last_exc


async def create_and_save_summary_async(
    markdown_text: str,
    settings: Settings,
    output_path: Path,
    original_filename: str,
):
    """
    Llama al LLM para generar un resumen para cada página y lo guarda.
    """
    summary_data = {
        "title": original_filename,
        "source": "Generated by background task",
        "blocks": [],
    }

    # --- INICIO DE LA CORRECCIÓN ---
    # 1. Parsea el texto en páginas individuales
    pages = _extract_pages_from_text(markdown_text)

    # 2. Define la función que llama al LLM para un chunk de páginas
    async def call_summarize_chunk(pages_chunk: List[Tuple[int, str]]):
        payload = {"pages": pages_chunk}
        async with _httpx_client(settings) as client:
            r = await client.post("/summarize_chunk", json=payload)
            r.raise_for_status()
            return r.json()

    # 3. Itera sobre cada página y la resume
    for page_num, page_content in pages:
        try:
            # Enviamos cada página como un chunk de una sola página
            result = await _retry(call_summarize_chunk, [(page_num, page_content)], retries=1, delay=1.5)
            block = result if isinstance(result, dict) else {"summary": str(result)}
            summary_data["blocks"].append(block)
        except Exception as e:
            logger.warning("Fallo al llamar a /summarize_chunk para pág %s, se usará placeholder: %s", page_num, e)
            summary_data["blocks"].append({"summary": f"Resumen de ejemplo para la página {page_num}."})
    # --- FIN DE LA CORRECCIÓN ---

    try:
        logic.save_hierarchical_summary(summary_data, output_path)
        logger.info("Resumen guardado en %s", output_path)
    except Exception as e:
        logger.exception("Error al guardar el resumen en segundo plano para %s: %s", output_path, e)


def create_and_save_summary(
    markdown_text: str,
    settings: Settings,
    output_path: Path,
    original_filename: str,
):
    """Wrapper síncrono para BackgroundTasks."""
    asyncio.run(
        create_and_save_summary_async(
            markdown_text=markdown_text,
            settings=settings,
            output_path=output_path,
            original_filename=original_filename,
        )
    )


# --------------------------------
# Endpoints
# --------------------------------

@app.post(
    "/process_document/",
    response_model=ProcessResponse,
    summary="Procesa un único documento PDF",
    dependencies=[Depends(require_api_key)],
)
async def process_document(
    background_tasks: BackgroundTasks,
    username: str = Form(..., min_length=1, max_length=120),
    file: UploadFile = File(...),
    settings: Settings = Depends(get_settings),
):
    t0 = time.perf_counter()

    if not file.filename:
        raise HTTPException(status_code=400, detail="El archivo no tiene nombre.")

    pdf_bytes = await file.read()
    if not pdf_bytes:
        raise HTTPException(status_code=400, detail="El archivo subido está vacío.")
    if len(pdf_bytes) > settings.max_pdf_bytes:
        raise HTTPException(
            status_code=413,
            detail=f"El archivo excede el límite ({settings.max_pdf_bytes} bytes).",
        )

    user_folder = settings.base_dir / logic.slugify(username)

    try:
        markdown_content = logic.convert_pdf_to_markdown(pdf_bytes)
        if not markdown_content:
            raise HTTPException(status_code=400, detail="La conversión a Markdown no produjo contenido.")
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error crítico en la conversión a Markdown: {e}")

    snippet = markdown_content[: settings.classify_snippet_len]
    try:
        existing_categories = logic.get_existing_categories(user_folder)
        payload = {"text": snippet, "categories": existing_categories}
        async with _httpx_client(settings) as client:
            r = await client.post("/classify", json=payload)
            r.raise_for_status()
            classification = r.json() or {}
        main_cat = classification.get("main_category") or "Sin-Clasificar"
        sub_cat = classification.get("sub_category") or "General"
    except httpx.HTTPError as e:
        raise HTTPException(status_code=503, detail=f"No se pudo conectar con el LLM Service: {e}")

    filename_base = Path(file.filename).stem
    try:
        md_path = logic.save_markdown_to_folder(
            markdown_content, user_folder, filename_base, main_cat, sub_cat
        )
        pdf_path = logic.save_pdf_to_folder(
            pdf_bytes, user_folder, file.filename, main_cat, sub_cat
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error al guardar archivos en el disco: {e}")

    summary_filename = md_path.with_suffix(".summary.json").name
    summary_path = md_path.parent / summary_filename

    background_tasks.add_task(
        create_and_save_summary,
        markdown_text=markdown_content,
        settings=settings_instance,
        output_path=summary_path,
        original_filename=file.filename,
    )

    elapsed = time.perf_counter() - t0
    logger.info("Procesado %s en %.2fs -> %s / %s", file.filename, elapsed, md_path, pdf_path)

    return ProcessResponse(
        message=f"Archivo '{file.filename}' recibido; resumen en segundo plano.",
        original_filename=file.filename,
        markdown_path=str(md_path),
        pdf_path=str(pdf_path),
        category=f"{main_cat}/{sub_cat}",
        summary_path=str(summary_path),
    )


@app.get("/", summary="Endpoint de estado")
async def read_root():
    return {"status": "Document Processor Service is running"}